export const FETCH_EXAMPLE_NEWS = 'FETCH_EXAMPLE_NEWS';
export const FETCH_EXAMPLE_NEWS_LOADING = 'FETCH_EXAMPLE_NEWS_LOADING';
export const FETCH_EXAMPLE_NEWS_SUCCESS = 'FETCH_EXAMPLE_NEWS_SUCCESS';
export const FETCH_EXAMPLE_NEWS_FAILURE = 'FETCH_EXAMPLE_NEWS_FAILURE';
